### ISSUE TITLE
Proxy status ON/OFF

### ISSUE THREAD

**Issue by 4ngel2769** [Zebradil/cloudflare-dynamic-dns#101]
When running the command in a terminal, all affected domains/subdomains' proxy status is set to off `DNS only`. Is there a flag that can set the proxy status to on `Proxied` for every domain/subdomain?

**Comment by Zebradil** [comment]
No, this is not supported currently but can be implemented.

Have you tried to manually switch it on after a record is created by cloudflare-dynamic-dns? I wonder if it stays this way after a record is updated again. If it stays enabled, this might be a workaround for you until the future is implemented (and I why it should not be, so I will add it).

**Comment by 4ngel2769** [comment]
After each run of cloudflare-dynamic-dns the proxy gets turned off and i have to manually turn it back on for many subdomains. It'd be supper handy to have a flag that switches it on or off 🚀

**Comment by Zebradil** [comment]
Oh, that's bad. I'll take a look into that.

**Comment by Zebradil** [comment]
https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/4.0.7 should fix the bug. There was an unhandled case in which a single record was not updated but re-created instead.

You still have to enable `proxy` manually but only for new records (e.g. if you setup a new domain or add more IPs via the `multihost` mode).

I'll add an option to control `proxy` setting for managed DNS records as a next step.

**Comment by Zebradil** [comment]
`--proxy=[auto,enabled,disabled]` flag is added in https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/4.1.0
