### ISSUE TITLE
ZoneID Error

### ISSUE THREAD

**Issue by 4ngel2769** [Zebradil/cloudflare-dynamic-dns#109]
After the 4.2.1 (as well as 4.2.2) cloudflare-ddns throws the following error:
```
FATA[0047] Couldn't get ZoneID   error="ListZonesContext command failed: HTTP request failed: Get \"https://api.cloudflare.com/client/v4/zones?name=mydomain.tld&per_page=50\": dial tcp: lookup api.cloudflare.com on 100.100.100.100:53: read udp 100.76.145.12:52005->100.100.100.100:53: i/o timeout"
```
The yaml config file contains:
- `iface: eth0`
- `token: ####` (with zone access)
- `proxy: enabled`
- `domains: ` (list of subdomains)
- `host-id: hostid`

**Comment by Zebradil** [comment]
It looks like an issue with tailscale DNS. We need more information here.

- Try to curl this domain and see if the issue repeats
- If yes, restart the tailscale service or go though their troubleshooting tips
- If it doesn't, try an earlier version of the program 

Tomorrow I'll also check how it's working on my machines (they run tailscale too).

**Comment by Zebradil** [comment]
Tested on my machines with 4.2.2. No issues noticed.

**Comment by 4ngel2769** [comment]
> It looks like an issue with tailscale DNS. We need more information here.

Didn't notice that, I'll turn it off and see the outcome.

**Comment by 4ngel2769** [comment]
After turning off Tailscale cloudflareddns runs perfectly! Thanks for pointing out Tailscale

**Comment by Zebradil** [comment]
No problem. We too have issues with tailscale DNS from time to time.
