### ISSUE TITLE
Issue getting zone name with domains that has more than two parts

### ISSUE THREAD

**Issue by maharjanmilan** [Zebradil/cloudflare-dynamic-dns#125]
I was using my domain name `*.example.com.np` where the zone is `example.com.np`. 
But I see that 
```

func getZoneFromDomain(domain string) string {
	parts := strings.Split(domain, ".")
	return strings.Join(parts[len(parts)-2:], ".")
}
```

This returns only `com.np` instead of `example.com.np`. So it returns error that says couldnot find zone.

**Comment by Zebradil** [comment]
Thanks for reporting, I'll take a look.

**Comment by maharjanmilan** [comment]
Thanks 🙏

**Comment by Zebradil** [comment]
Should be fixed in https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/4.2.12

**Comment by maharjanmilan** [comment]
Works like a charm. Thank you for the quick fix 🙌
