### ISSUE TITLE
Please add the possibility to get ip4/6 from web

### ISSUE THREAD

**Issue by badrazizi** [Zebradil/cloudflare-dynamic-dns#129]
For example using api.ipify.org for ip4 or using api64.ipify.org for ip6.
also if you can make it configurable to point where to get ipv4 and ipv6.

```
iface: eth0
token: cloudflare-api-token
domains:
  - example.com
  - "*.example.com"
```
into 
```
webv4: api.ipify.org
webv6: api64.ipify.org
token: cloudflare-api-token
domains:
  - example.com
  - "*.example.com"
```

**Comment by Zebradil** [comment]
I think it makes more sense to provide a hook for retrieving IPs. Something like:

```yaml
ipv4: curl -fsSL https://api.ipify.org
ipv6: curl -fsSL https://api6.ipify.org
```

This way any provider or some other source of IP addresses can be used.

Would this cover your use case?

**Comment by badrazizi** [comment]
Yes thank you

**Comment by badrazizi** [comment]
Would we be able to use script instead of curl in case the response is json formatted?

**Comment by Zebradil** [comment]
> Would we be able to use script

Yes, that's the idea. You'll be able to use any custom script or program.

I'll look into this during the weekend.

**Comment by Zebradil** [comment]
I gave it a thought and I think that `ipcmd` instead of `ipv4`/`ipv6` should do. The IP stack is set via the `stack` option and there is no need to duplicate this.

**Comment by badrazizi** [comment]
yes indeed, based on the IPStack you can treat it ether as ipv4 or ipv6

**Comment by Zebradil** [comment]
The `--ipcmd` option is now available in https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/4.3.0

**Comment by badrazizi** [comment]
thanks
