### ISSUE TITLE
Release MIPS Linux builds for OpenWrt 

### ISSUE THREAD

**Issue by GalacticLion7** [Zebradil/cloudflare-dynamic-dns#38]
Hello,

Could you release MIPS Linux builds for use in OpenWrt routers and other embedded devices? It is very easy to compile a Go application for MIPS Linux.

Thank you.

**Comment by Zebradil** [comment]
Hi @GalacticLion7,

Thank you for the request. I've added MIPS architectures to the list of artefacts to build.

The [new release 2.0.1](https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.0.1) contains them. Could you check if it works for you?
