### ISSUE TITLE
client registering wrong ipv6 address

### ISSUE THREAD

**Issue by jbeez** [Zebradil/cloudflare-dynamic-dns#46]
Not sure if this is my fault or a code issue, my interface (enp0s4) has 3 v6 addresses, an fe80: address, a public address starting with 2600:, and an fdeb: address. Is there a way to tell it to ignore the fdeb address, because it's registering that in my zone instead of the 2600 address.

Thanks

**Comment by Zebradil** [comment]
The tool uses the first global unicast IP (as it is implemented in [IP.IsGlobalUnicast()](https://pkg.go.dev/inet.af/netaddr#IP.IsGlobalUnicast)) on the specified interface.

There is no way to influence that now, but we can add something like excluding or including regex, subnet prefixes, or something like that.

**Comment by jbeez** [comment]
I was just doing some tcpdump snooping on my lan and it looks like Apple TV units are actually the culprits here, handing out ULA addressing for whatever reason via RAs, possibly for "Thread"? I don't even know what that is.

**Comment by Zebradil** [comment]
Please, check with https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.1.0 or https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.1.1

With the new releases, you can now [specify preferred subnets](https://github.com/Zebradil/cloudflare-dynamic-dns#priority-subnets).
