### ISSUE TITLE
Ignore ULA addresses as part of an update

### ISSUE THREAD

**Issue by vicmike** [Zebradil/cloudflare-dynamic-dns#51]
Hi there,

Recently I enabled ULA on my network and noticed that the program was updating my public DNS with ULA entries;

```console
mikew@XXX:~/temp $ ./cloudflare-dynamic-dns
INFO[0000] Using config file:/home/mikew/.cloudflare-dynamic-dns.yaml
INFO[0000] Setting log level to:info
INFO[0000] Configuration                                 domains="[xxx]" iface=wlan0 prioritySubnets="[]" stateFilepath= systemd=false token="[40 characters]" ttl=1
INFO[0000] Found 3 public IPv6 addresses, selected fd8a:e1e4:16f9:179e:b10a:d4b1:6342:25c8  addresses="[fd8a:e1e4:16f9:179e:b10a:d4b1:6342:25c8 2604:3d08:xxxx::11c0 2604:3d08:xxxx:fe36]"
```

I updated to 2.1.1 and made use of the PrioritySubnets feature to simply include my ISPs entire v6 allocation so the problem is "solved", but I wonder if it's worthwhile to exclude anything that is not publicly routable when updating public DNS.

**Comment by vicmike** [comment]
Perhaps the code could just look for addresses falling under 2000::/3 as that encompasses all of the publicly routed IPv6 space, and if someone needs to publish ULA addresses they could add them to the PrioritySubnets section.

**Comment by Zebradil** [comment]
Hi @vicmike, thank you for the suggestion.

Yes, it makes sense to prioritize publicly routable addresses by default. I'll take a look into it.

**Comment by Zebradil** [comment]
Hey @vicmike, I finally got time to finish this. Could you check if https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.4.0 works for you?
