### ISSUE TITLE
Ignore SLAAC privacy addresses?

### ISSUE THREAD

**Issue by philipl** [Zebradil/cloudflare-dynamic-dns#58]
I've recently started using cloudflare-dynamic-dns to publish my server's IPv6 address, and it's working very well with one caveat.

On any modern OS using SLAAC, the privacy extension will be turned on by default, which causes short lived random addresses to be generated for the interface to be used to anonymize outgoing traffic. These addresses are not practically usable as the IP behind our DNS names because they change all the time. Rather, we want to register the stable EUI-64 address based on the MAC address.

Today, the tool's default behaviour causes it to pick any assigned address at random, as they are all equally acceptable for the current logic - they have the same subnet prefix, etc.

To make it pick the EUI-64 address, I had to use a /72 priority subnet prefix that incorporates the first part of the stable EUI-64 address. This works, but it now means I've had to hard-code the /64 that my ISP assigned me, and if that changes, my configuration would need to be manually changed as well.

Ideally, the tool would be able to prioritize the EUI-64 address (by matching against the interface MAC address) automatically.

Thanks!

**Comment by Zebradil** [comment]
Hey @philipl, I finally got some time to look into that. Could you check if this is fixed with https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.5.0 ?

**Comment by philipl** [comment]
@Zebradil Thanks for looking at this, but it did not work. I ensured I had the EUI-64 address and a privacy address and it kept picking the privacy one. It also didn't print the warning about using an unstable IP address. I tried both the deb and tar.gz binaries from the release page.

**Comment by Zebradil** [comment]
@philipl thanks for the quick feedback!

Could you share the IPv6 addresses you deal with (probably change a few last bits to be safe, or send them to github-inbox@zeb.mozmail.com)?

It may be also helpful to run cloudflare-dynamic-dns with `--log-level=debug`.

**Comment by philipl** [comment]
Thanks. I emailed you the logs.

**Comment by Zebradil** [comment]
Hi @philipl, thank you for the logs. The IPs helped a lot. There was an error in the EUI-64 detection code. Let's see if it is fixed in https://github.com/Zebradil/cloudflare-dynamic-dns/releases/tag/2.6.1

**Comment by philipl** [comment]
Thanks! Amusingly, I've just replaced my home router and it's refusing to do stateless autoconfig and forcing stateful dhcpv6 so I can't actually test this right now. I've got to fix the router first. *sigh*

**Comment by philipl** [comment]
And I managed to fix it. After that I can confirm it's picking the EUI-64 address. Thanks!

**Comment by Zebradil** [comment]
Awesome! Thanks for the help with testing and debugging.
